/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tv-brand':          '#7c45b0',
        'tv-brand-hover':    '#653a92',
        'tv-brand-bg':       '#995cd3',
        'tv-brand-tint':     '#f3eeff',
        'tv-surface':        '#f5f3fa',
        'tv-surface-hover':  '#ede5f7',
        'tv-surface-active': '#e4daef',
        'tv-surface-muted':  '#fafbfc',
        'tv-border-strong':  '#b5a4cd',
        'tv-border':         '#d4c4e8',
        'tv-border-light':   '#e0daea',
        'tv-border-divider': '#f0eaf8',
        'tv-text-primary':   '#242436',
        'tv-text-secondary': '#737373',
        'tv-text-label':     '#5d5e65',
        'tv-text-brand':     '#7c45b0',
        'tv-text-decorative':'#b5a4cd',
        'tv-success':        '#15803d',
        'tv-success-bg':     '#f0fdf4',
        'tv-success-border': '#bbf7d0',
        'tv-info':           '#0e7490',
        'tv-info-bg':        '#e0f8ff',
        'tv-info-border':    '#7dd8f5',
        'tv-warning':        '#b45309',
        'tv-warning-bg':     '#fffbeb',
        'tv-warning-border': '#fde68a',
        'tv-danger':         '#dc2626',
        'tv-danger-bg':      '#fef2f2',
        'tv-danger-border':  '#fecaca',
        'tv-record':         '#007c9e',
        'tv-record-hover':   '#005d77',
        'tv-record-bg':      '#00c0f5',
        'tv-record-tint':    '#d9f2f8',
        'tv-record-border':  '#8dd9ed',
      },
      fontFamily: {
        display: ['Fraunces', 'Roboto', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
